/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sisvac.app.gui;

/**
 *
 * @author frank
 */
public class BloqueLoginGui extends javax.swing.JPanel {
    private GestorGui gestorGui;
    /**
     * Creates new form PanelLogin2
     */
    

    public BloqueLoginGui(GestorGui gestorGui) {
        this.gestorGui = gestorGui;
        initComponents();
    }

    

    private void logInitialization() {
        System.out.println("PanelLogin initialization started...");
        // Puedes agregar más logs según sea necesario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txtpass = new javax.swing.JPasswordField();
        Txtuser = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        loginMsg = new javax.swing.JLabel();

        Txtpass.setBackground(new java.awt.Color(255, 204, 204));
        Txtpass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Txtpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txtpass.setText("Password");
        Txtpass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        Txtuser.setBackground(new java.awt.Color(255, 204, 204));
        Txtuser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Txtuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txtuser.setText("Usuario");
        Txtuser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Iniciar Sesion");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        loginMsg.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(loginMsg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(Txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(loginMsg)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        System.out.println(" boton login presionado");
         // Cambiar la programacion
            String userDni = Txtuser.getText();
            switch(userDni){
                case "1": gestorGui.mostrarPanel("colaborador"); break;
                case "2": gestorGui.mostrarPanel("jefe");break;
                case "3": gestorGui.mostrarPanel("visor"); break;
                case "4": gestorGui.mostrarPanel("editor"); break;

            }
        
        /*GestorGui gui = GestorGui.getInstance();
        gui.initializeMainFrame();
        gui.mostrarPanelColaborador();
        gui.showFrame();*/
        
        
        
/*        boolean esUsuario = theLogin.ingresar(
            Txtuser.getText(),
            new String(Txtpass.getPassword()));
        System.out.println(""+esUsuario);
        if( esUsuario ){
            //theLogin.getUloged_dni();
            //theLogin.getUloged_tipo();
            //appUsuario
            /* switch("fr"){
                case: "colaborador"; break;
                case: "jefe"; break;
            }*/
            /**//*this.setVisible(false);
            PanelUJefe pnlUsuario = new PanelUJefe();
            pnlUsuario.setVisible(true);*/
/*
            System.out.println("logueado");
        }else{
            loginMsg.setText(theLogin.getMensaje() );j
       */
            //ControlPanelU panelUsuario = GestorPanelU.getInstance();
           // panelUsuario.panel("colaborador");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Txtpass;
    private javax.swing.JTextField Txtuser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel loginMsg;
    // End of variables declaration//GEN-END:variables
}
