/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sisvac.app.gui;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author frank
 */
public class Header extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Header(String f) {
        
        
        
        initComponents();
       /* setBorder(new CompoundBorder(
                new LineBorder(new Color(51, 0, 255)),
                new ToolDegradadoBordeBajo(Color.BLUE, Color.WHITE, 20)
        ));

        Border bordeInferior = BorderFactory.createMatteBorder(0, 0, 20, 0, new Color(239, 239, 239));
        this.setBorder(new CompoundBorder(this.getBorder(), bordeInferior));
*/
       /*Border bordeInferior = BorderFactory.createMatteBorder(0, 0, 20, 0, new Color(239, 239, 239));
            
        this.headerLeft.setBorder(bordeInferior);
        this.headerRight.setBorder(bordeInferior);
        this.headerCenter.setBorder(bordeInferior);
       // jLabel1.setText(f);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLeft = new javax.swing.JPanel();
        headerCenter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        headerRight = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(512, 50));
        setLayout(new java.awt.GridLayout(1, 0));

        headerLeft.setBackground(new java.awt.Color(255, 255, 255));
        headerLeft.setPreferredSize(new java.awt.Dimension(255, 50));

        javax.swing.GroupLayout headerLeftLayout = new javax.swing.GroupLayout(headerLeft);
        headerLeft.setLayout(headerLeftLayout);
        headerLeftLayout.setHorizontalGroup(
            headerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        headerLeftLayout.setVerticalGroup(
            headerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(headerLeft);

        headerCenter.setBackground(new java.awt.Color(255, 255, 255));
        headerCenter.setPreferredSize(new java.awt.Dimension(255, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Hola, Frank Valle");

        javax.swing.GroupLayout headerCenterLayout = new javax.swing.GroupLayout(headerCenter);
        headerCenter.setLayout(headerCenterLayout);
        headerCenterLayout.setHorizontalGroup(
            headerCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerCenterLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        headerCenterLayout.setVerticalGroup(
            headerCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(headerCenter);

        headerRight.setBackground(new java.awt.Color(255, 255, 255));
        headerRight.setPreferredSize(new java.awt.Dimension(255, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(24, 24, 24));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logout-rounded-20.png"))); // NOI18N
        jButton1.setText("Cerrar Sesion");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 239, 239), 1, true));
        jButton1.setFocusCycleRoot(true);
        jButton1.setIconTextGap(5);
        jButton1.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jButton1.setMaximumSize(new java.awt.Dimension(70, 28));
        jButton1.setMinimumSize(new java.awt.Dimension(70, 28));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerRightLayout = new javax.swing.GroupLayout(headerRight);
        headerRight.setLayout(headerRightLayout);
        headerRightLayout.setHorizontalGroup(
            headerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerRightLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerRightLayout.setVerticalGroup(
            headerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerRightLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        add(headerRight);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel headerCenter;
    private javax.swing.JPanel headerLeft;
    private javax.swing.JPanel headerRight;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
