
package sisvac.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;

import sisvac.ManejadorDatos;
import sisvac.ManejadorSesion;
import sisvac.model.Trabajador;

public class BloqueInColaboradoresGui extends javax.swing.JPanel {
    
    public BloqueInColaboradoresGui() {
        System.out.println("colaboradores ");
        initComponents();
        actualizarData();
    }

    public final void actualizarData(){
       
       this.boxColaboradores.setLayout(new BoxLayout(this.boxColaboradores, BoxLayout.Y_AXIS));
       System.out.println("actualizar: ");
       
       ManejadorSesion appSesion = ManejadorSesion.getInstance(); 
        
       ManejadorDatos datosGui = new ManejadorDatos(); 
       List<Trabajador> trabajadorList = datosGui.buscarColaboradores(appSesion.getDni());
       //this.boxColaboradores.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));

        System.out.println("num elementos: "+trabajadorList.size());
        elementoColaboradorItem eColaborador;   
        for(Trabajador t : trabajadorList){
             System.out.println(t.getDni()+",???? ");
              eColaborador = new elementoColaboradorItem(t);
             //eColaborador.actualizarData(t);
             this.boxColaboradores.add(eColaborador);
        }
       if( trabajadorList.size() > 1){
           this.boxColaboradores.setPreferredSize(new Dimension(760, trabajadorList.size() * 150));
           this.jPanel2.setPreferredSize(new Dimension(800, ((trabajadorList.size() * 150)+80)));

       }
       
       
       /*
       this.boxColaboradores.add(eColaborador);
                
       Colector2 colector = new Colector2("40740030"); 
       System.out.println("el codigo trabja ::: "+ colector.empleado.getCodigo());
     /*  emp_codigo.setText(  "COD "+colector.empleado.getCodigo() );
       emp_cargo.setText(  " -  "+colector.empleado.getCargo() );
       emp_dni.setText(  colector.empleado.getDni() );
       emp_nombre.setText(  colector.empleado.getNombre() );
       emp_inicio.setText(  colector.empleado.getFecha_ingreso() );*/
     
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        boxColaboradores = new javax.swing.JPanel();

        jLabel12.setText("jLabel12");

        setBackground(new java.awt.Color(243, 243, 243));
        setName("contenedor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(840, 839));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 668));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(93, 43, 255));
        jLabel2.setText("Colaboradores a Cargo");

        jSeparator2.setForeground(new java.awt.Color(239, 239, 239));

        boxColaboradores.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout boxColaboradoresLayout = new javax.swing.GroupLayout(boxColaboradores);
        boxColaboradores.setLayout(boxColaboradoresLayout);
        boxColaboradoresLayout.setHorizontalGroup(
            boxColaboradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        boxColaboradoresLayout.setVerticalGroup(
            boxColaboradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(boxColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(boxColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxColaboradores;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
