
package sisvac.gui;


import sisvac.ManejadorDatos;
import sisvac.ManejadorSesion;
import sisvac.model.Trabajador;

/**
 *
 * @author frank
 */
public class BloqueInEmpleadoGui extends javax.swing.JPanel {
    /**
     * Creates new form PanelLogin2
     */
    public BloqueInEmpleadoGui() {
         initComponents();
        actualizarData();
    }
    public void actualizarData(String dni){
       ManejadorDatos datosGui = new ManejadorDatos(); 
       Trabajador empleado = datosGui.buscarTrabajador( dni ); 
       
       System.out.println("el codigo trabja ::: "+ empleado.getCodigo());
       emp_codigo.setText(  "CODv "+empleado.getCodigo() );
       emp_cargo.setText(  " -  "+empleado.getCargo() );
       emp_dni.setText(  empleado.getDni() );
       emp_nombre.setText(  empleado.getNombre() );
       emp_inicio.setText(  empleado.getFecha_ingreso() );
    }
    public void actualizarData(){
        ManejadorSesion appSesion = ManejadorSesion.getInstance(); 
        actualizarData( appSesion.getDni() );
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        emp_nombre1 = new javax.swing.JLabel();
        emp_cargo1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emp_codigo1 = new javax.swing.JLabel();
        emp_dni1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        emp_inicio1 = new javax.swing.JLabel();
        emp_acumulado1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        emp_nombre = new javax.swing.JLabel();
        emp_cargo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emp_codigo = new javax.swing.JLabel();
        emp_dni = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emp_inicio = new javax.swing.JLabel();
        emp_acumulado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanel2.setPreferredSize(new java.awt.Dimension(840, 250));

        jPanel3.setBackground(new java.awt.Color(252, 252, 252));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 51), 1, true));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario (1).png"))); // NOI18N

        emp_nombre1.setBackground(new java.awt.Color(255, 255, 255));
        emp_nombre1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        emp_nombre1.setForeground(new java.awt.Color(48, 48, 48));
        emp_nombre1.setText("Jefe");
        emp_nombre1.setAlignmentY(0.0F);
        emp_nombre1.setPreferredSize(new java.awt.Dimension(224, 35));

        emp_cargo1.setBackground(new java.awt.Color(93, 43, 255));
        emp_cargo1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        emp_cargo1.setForeground(new java.awt.Color(93, 43, 255));
        emp_cargo1.setText(" - Jefe de Almacen");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(63, 63, 69));
        jLabel7.setText("DNI ");

        emp_codigo1.setBackground(new java.awt.Color(93, 43, 255));
        emp_codigo1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        emp_codigo1.setForeground(new java.awt.Color(93, 43, 255));
        emp_codigo1.setText("COD 000123");

        emp_dni1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emp_dni1.setForeground(new java.awt.Color(24, 24, 24));
        emp_dni1.setText("40740030");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(63, 63, 69));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Inicio Labores");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(63, 63, 69));
        jLabel14.setText("Dias  acumulados");

        emp_inicio1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emp_inicio1.setForeground(new java.awt.Color(63, 63, 69));
        emp_inicio1.setText("14-01-1981");

        emp_acumulado1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emp_acumulado1.setForeground(new java.awt.Color(63, 63, 69));
        emp_acumulado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emp_acumulado1.setText("30 dias");

        jSeparator2.setBackground(new java.awt.Color(239, 239, 239));
        jSeparator2.setForeground(new java.awt.Color(239, 239, 239));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setBackground(new java.awt.Color(239, 239, 239));
        jSeparator4.setForeground(new java.awt.Color(239, 239, 239));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-calendar-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(emp_codigo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emp_cargo1))
                    .addComponent(emp_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emp_dni1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emp_inicio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(emp_acumulado1))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emp_cargo1)
                            .addComponent(emp_codigo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator4)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(emp_dni1))
                                                    .addComponent(jLabel25)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(emp_acumulado1)))
                                        .addGap(20, 20, 20))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emp_inicio1)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        setBackground(new java.awt.Color(243, 243, 243));
        setPreferredSize(new java.awt.Dimension(840, 250));

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 210));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario (1).png"))); // NOI18N

        emp_nombre.setBackground(new java.awt.Color(255, 255, 255));
        emp_nombre.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        emp_nombre.setForeground(new java.awt.Color(48, 48, 48));
        emp_nombre.setText("Jefe");
        emp_nombre.setAlignmentY(0.0F);
        emp_nombre.setPreferredSize(new java.awt.Dimension(224, 35));

        emp_cargo.setBackground(new java.awt.Color(93, 43, 255));
        emp_cargo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        emp_cargo.setForeground(new java.awt.Color(93, 43, 255));
        emp_cargo.setText(" - Jefe de Almacen");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(63, 63, 69));
        jLabel6.setText("DNI ");

        emp_codigo.setBackground(new java.awt.Color(93, 43, 255));
        emp_codigo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        emp_codigo.setForeground(new java.awt.Color(93, 43, 255));
        emp_codigo.setText("COD 000123");

        emp_dni.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emp_dni.setForeground(new java.awt.Color(24, 24, 24));
        emp_dni.setText("40740030");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(63, 63, 69));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Inicio Labores");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(63, 63, 69));
        jLabel13.setText("Dias  acumulados");

        emp_inicio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emp_inicio.setForeground(new java.awt.Color(63, 63, 69));
        emp_inicio.setText("14-01-1981");

        emp_acumulado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emp_acumulado.setForeground(new java.awt.Color(63, 63, 69));
        emp_acumulado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emp_acumulado.setText("30 dias");

        jSeparator1.setBackground(new java.awt.Color(239, 239, 239));
        jSeparator1.setForeground(new java.awt.Color(239, 239, 239));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setBackground(new java.awt.Color(239, 239, 239));
        jSeparator3.setForeground(new java.awt.Color(239, 239, 239));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-calendar-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emp_codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emp_cargo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emp_dni)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emp_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(emp_acumulado)))
                    .addComponent(emp_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emp_cargo)
                            .addComponent(emp_codigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(emp_dni))
                                                    .addComponent(jLabel24)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(emp_acumulado)))
                                        .addGap(20, 20, 20))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emp_inicio)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emp_acumulado;
    private javax.swing.JLabel emp_acumulado1;
    private javax.swing.JLabel emp_cargo;
    private javax.swing.JLabel emp_cargo1;
    private javax.swing.JLabel emp_codigo;
    private javax.swing.JLabel emp_codigo1;
    private javax.swing.JLabel emp_dni;
    private javax.swing.JLabel emp_dni1;
    private javax.swing.JLabel emp_inicio;
    private javax.swing.JLabel emp_inicio1;
    private javax.swing.JLabel emp_nombre;
    private javax.swing.JLabel emp_nombre1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
