
package sisvac.gui;

import sisvac.ManejadorGui;
import java.util.ArrayList;
import java.util.List;

import sisvac.ManejadorDatos;
import sisvac.model.Trabajador;
import sisvac.model.Vacacion;


public class elementoColaboradorItem extends javax.swing.JPanel {
    /**
     * Creates new form PanelLogin2
     */
    private String dni;
    private String codigo;
    public elementoColaboradorItem(Trabajador t) {
         initComponents();
        actualizarData(t);
    }

    public final void actualizarData(Trabajador t){
        
            //eAcumulado = t.getCargo();
        eCodCargo.setText(t.getCargo());
        eDni.setText(t.getDni());
        eFinicio.setText(t.getFecha_ingreso());
        eNombre.setText(t.getNombre());
      
     
    }
    public void mostrarVacaciones(){
        ManejadorDatos datosGui = new ManejadorDatos(); 
        List<Vacacion> vacacionList = datosGui.buscarVacaciones(dni);
        mostrarVacaciones( vacacionList);
    }
    public void mostrarVacaciones(List<Vacacion> vacacionList){
        elementoVacacionItem eVacacionItem;
        
        boxVacaciones.removeAll();
        for(Vacacion vacacionFila:vacacionList){
            eVacacionItem = new elementoVacacionItem();
            eVacacionItem.setData(  vacacionFila.getNum_dias(),
                                    vacacionFila.getFecha_inicio(),
                                    vacacionFila.getFecha_fin()) ;
            // Limpiar el contenido del panelB
            boxVacaciones.add(eVacacionItem);
            
            System.out.println("se agrego la vacion");
        }
        
        ManejadorDatos datosGui = new ManejadorDatos(); 
        datosGui.actualizarVacacion(vacacionList, dni); 
        System.out.println("se intento ingresar a la BD");
        boxVacaciones.revalidate();
        
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        boxEmpleado = new javax.swing.JPanel();
        eNombre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eDni = new javax.swing.JLabel();
        eCodCargo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        eFinicio = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        eAcumulado = new javax.swing.JLabel();
        boxVacaciones = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 243, 243));
        setPreferredSize(new java.awt.Dimension(840, 140));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.jpg"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.EAST);

        boxEmpleado.setBackground(new java.awt.Color(252, 252, 252));
        boxEmpleado.setMaximumSize(new java.awt.Dimension(350, 32767));
        boxEmpleado.setPreferredSize(new java.awt.Dimension(320, 184));

        eNombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eNombre.setText("Juan Alvares Diaz Suarez");
        eNombre.setMaximumSize(new java.awt.Dimension(200, 22));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setText("DNI : ");

        eDni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eDni.setText("40740030");

        eCodCargo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eCodCargo.setText("COD 1522 - Operario");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel15.setText("F. Inicio Laboral");

        eFinicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eFinicio.setText("14-10-2021");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel17.setText("Dias Acumulado");

        eAcumulado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eAcumulado.setText("30 dias");

        javax.swing.GroupLayout boxEmpleadoLayout = new javax.swing.GroupLayout(boxEmpleado);
        boxEmpleado.setLayout(boxEmpleadoLayout);
        boxEmpleadoLayout.setHorizontalGroup(
            boxEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxEmpleadoLayout.createSequentialGroup()
                .addGroup(boxEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxEmpleadoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(boxEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eCodCargo)))
                    .addGroup(boxEmpleadoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(boxEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(boxEmpleadoLayout.createSequentialGroup()
                                .addGroup(boxEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(boxEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eFinicio)
                                    .addComponent(eDni)))
                            .addGroup(boxEmpleadoLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eAcumulado)))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        boxEmpleadoLayout.setVerticalGroup(
            boxEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxEmpleadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(eCodCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(eDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(eFinicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(eAcumulado))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        add(boxEmpleado, java.awt.BorderLayout.WEST);

        boxVacaciones.setBackground(new java.awt.Color(252, 252, 252));
        boxVacaciones.setMaximumSize(new java.awt.Dimension(400, 20));
        boxVacaciones.setPreferredSize(new java.awt.Dimension(400, 16));
        boxVacaciones.setLayout(new javax.swing.BoxLayout(boxVacaciones, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        boxVacaciones.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-calendar-16.png"))); // NOI18N
        jLabel22.setText("7 dias");

        jLabel25.setText("11-07-2024");

        jLabel23.setText("10-01-2024");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        boxVacaciones.add(jPanel2);

        add(boxVacaciones, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      System.out.println("lanzar jframe clicked");
      ManejadorGui gui = ManejadorGui.getInstance();
      VentanaEditarVacacion ventana =new VentanaEditarVacacion(gui.getFrame(), true);
      ventana.setVisible(true);
      
      String[][] vData = ventana.getData();      
      List<Vacacion> vacacionList = new ArrayList();
      Vacacion  vacacionItem = new Vacacion();
      for (int i = 0; i < 4; i++) {
          vacacionItem.setNum_dias( Integer.parseInt(vData[i][0]));
          vacacionItem.setFecha_inicio( vData[i][1]);
          vacacionItem.setFecha_fin(vData[i][2]);
          vacacionItem.setCodigo_trabajador(Integer.parseInt(vData[i][3]));
          
          vacacionList.add(vacacionItem);
      }
      ManejadorDatos datosGui = new ManejadorDatos(); 
      datosGui.actualizarVacacion(vacacionList,dni);
      mostrarVacaciones(vacacionList);
      
      System.out.println(vacacionList);
      System.out.println("lanzar jframe end");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxEmpleado;
    private javax.swing.JPanel boxVacaciones;
    private javax.swing.JLabel eAcumulado;
    private javax.swing.JLabel eCodCargo;
    private javax.swing.JLabel eDni;
    private javax.swing.JLabel eFinicio;
    private javax.swing.JLabel eNombre;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
