
package sisvac.gui;



/**
 *
 * @author frank
 */
public class elementoVacacionItem extends javax.swing.JPanel {
    /**
     * Creates new form PanelLogin2
     */
    public elementoVacacionItem() {
         initComponents();
    }

    public void setData(int vdias,String vinicio,String vfin){
        vDias.setText( Integer.toString(vdias) ); 
        vDias.setText(vinicio);
        vDias.setText(vfin);
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        vDias = new javax.swing.JLabel();
        vInicio = new javax.swing.JLabel();
        vFin = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(840, 839));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);

        jPanel7.setBackground(new java.awt.Color(252, 252, 252));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel7.setLayout(new java.awt.GridLayout(1, 4));

        vDias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-calendar-16.png"))); // NOI18N
        vDias.setText("?? dias");
        jPanel7.add(vDias);

        vInicio.setText("00-00-0000");
        jPanel7.add(vInicio);

        vFin.setText("00-00-0000");
        jPanel7.add(vFin);

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel vDias;
    private javax.swing.JLabel vFin;
    private javax.swing.JLabel vInicio;
    // End of variables declaration//GEN-END:variables
}
