/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sisvac.gui;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.LineBorder;
import sisvac.ManejadorGui;
import sisvac.ManejadorSesion;

/**
 *
 * @author frank
 */
public class Header extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Header() {
        
        ManejadorSesion appSesion = ManejadorSesion.getInstance(); 
        System.out.println("tipo de session:" +appSesion.getUserId() + appSesion.getMsg() );
        
        initComponents();
        String tUsuario = appSesion.getUserTipo();
        tipoUsuario.setText(tUsuario.toUpperCase());
        
        String nUsuario = appSesion.getUserNombre();
        nombreUsuario.setText("Bienvenido, "+nUsuario);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLeft = new javax.swing.JPanel();
        tipoUsuario = new javax.swing.JLabel();
        headerCenter = new javax.swing.JPanel();
        nombreUsuario = new javax.swing.JLabel();
        headerRight = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(512, 50));
        setLayout(new java.awt.GridLayout(1, 0));

        headerLeft.setBackground(new java.awt.Color(255, 255, 255));
        headerLeft.setPreferredSize(new java.awt.Dimension(255, 50));

        tipoUsuario.setBackground(new java.awt.Color(0, 0, 255));
        tipoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoUsuario.setForeground(new java.awt.Color(0, 0, 153));
        tipoUsuario.setText("Colaborador");

        javax.swing.GroupLayout headerLeftLayout = new javax.swing.GroupLayout(headerLeft);
        headerLeft.setLayout(headerLeftLayout);
        headerLeftLayout.setHorizontalGroup(
            headerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerLeftLayout.setVerticalGroup(
            headerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(headerLeft);

        headerCenter.setBackground(new java.awt.Color(255, 255, 255));
        headerCenter.setPreferredSize(new java.awt.Dimension(255, 50));

        nombreUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.jpg"))); // NOI18N
        nombreUsuario.setText("Hola, Frank Valle");

        javax.swing.GroupLayout headerCenterLayout = new javax.swing.GroupLayout(headerCenter);
        headerCenter.setLayout(headerCenterLayout);
        headerCenterLayout.setHorizontalGroup(
            headerCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerCenterLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(nombreUsuario)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        headerCenterLayout.setVerticalGroup(
            headerCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        add(headerCenter);

        headerRight.setBackground(new java.awt.Color(255, 255, 255));
        headerRight.setPreferredSize(new java.awt.Dimension(255, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(24, 24, 24));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logout-rounded-20.png"))); // NOI18N
        jButton1.setText("Cerrar Sesion");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 239, 239), 1, true));
        jButton1.setFocusCycleRoot(true);
        jButton1.setIconTextGap(5);
        jButton1.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jButton1.setMaximumSize(new java.awt.Dimension(70, 28));
        jButton1.setMinimumSize(new java.awt.Dimension(70, 28));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerRightLayout = new javax.swing.GroupLayout(headerRight);
        headerRight.setLayout(headerRightLayout);
        headerRightLayout.setHorizontalGroup(
            headerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerRightLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerRightLayout.setVerticalGroup(
            headerRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(headerRight);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManejadorGui gestorGui = ManejadorGui.getInstance();
        gestorGui.mostrarPanel("login");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel headerCenter;
    private javax.swing.JPanel headerLeft;
    private javax.swing.JPanel headerRight;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JLabel tipoUsuario;
    // End of variables declaration//GEN-END:variables
}
